site_name: OpenMod Documentation
coypright: 'The OpenMod Documentation is licensed under the terms of the Creative Commons Attribution Share Alike 4.0 International license.'
docs_dir: 'content'
repo_name: 'openmod/openmod'
repo_url: 'https://github.com/openmod/openmod'
edit_uri: 'https://github.com/openmod/openmod-docs/edit/master/content/'
pages:
    - Home: index.md
    - User Guide:
        - Installation:
            - Unturned: user-guide/installation/unturned.md
        - Migration:
            - Migarting from RocketMod: user-guide/migration/rocketmod.md         
        - Plugins: 
            - Installing and Managing Plugins: user-guide/plugins/installation.md
        - OpenMod Concepts:
            - Configurations: user-guide/configuration/configurations.md
            - Translations: user-guide/configuration/translations.md
            - Permissions: user-guide/configuration/permissions.md
            - Logging: user-guide/configuration/logging.md
    - Development Guide:
        - Getting Started:
            - Making your first plugin: development-guide/getting-started/making-your-first-plugin.md
            - Commands: development-guide/getting-started/commands.md
            - Scheduling: development-guide/getting-started/scheduling.md
            - Logging: development-guide/getting-started/logging.md
            - Configurations: development-guide/getting-started/configurations.md
            - Permissions: development-guide/getting-started/permissions.md
        - Events:
            - OpenMod Events: development-guide/events/events.md
            - Built-in Events: development-guide/events/builtin-events.md
            - Game Events: development-guide/events/game-events.md            
    - About:
        - Documentation: about/documentation.md
plugins:
  - search
  - autoreflinks
theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'light blue'
  language: 'en'
  feature:
    tabs: true  
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde